### ISSUE TITLE
Python error when running StrainXpress on BMock12 dataset

### ISSUE THREAD

**Issue by cimendes** [kangxiongbin/StrainXpress#5]
Greeting,

I'm trying to integrate StrainXpress into [LMAS](https://github.com/B-UMMI/LMAS), a nextflow workflow enabling the benchmarking of traditional and metagenomic prokaryotic de novo assembly software using defined mock communities.

I've created a docker container, available at https://github.com/B-UMMI/LMAS/blob/main/docker/strainXpress/Dockerfile and in the [docker hub registry](https://hub.docker.com/r/cimendes/strainxpress/tags). 

When using [test data](https://github.com/B-UMMI/LMAS/blob/main/test/data/tiny_reads.fq.gz) (uncompressed) I'm able to obtain an assembly, but when trying to [recreate your results with the BMock12 community](https://academic.oup.com/nar/article/50/17/e101/6625806#373858745), with the original data downsampled to 10%, I run into the following error:

```bash
....
this is the: 168000000 for 100w lines
this is the: 169000000 for 100w lines
this is the: 170000000 for 100w lines
the 1/1 part finished...

##################################################
cat: cmd_polyte.sh: No such file or directory
[ERROR] failed to open file '../contigs_b.fastq'
cp: cannot stat '../contigs_b.fastq': No such file or directory
pipeline_per_stage.py
Traceback (most recent call last):
  File "/NGStools/StrainXpress/scripts/pipeline_per_stage.v3.py", line 668, in <module>
    sys.exit(main())
  File "/NGStools/StrainXpress/scripts/pipeline_per_stage.v3.py", line 102, in main
    original_readcount = get_original_readcount(args.fastq + '/singles.fastq')
  File "/NGStools/StrainXpress/scripts/pipeline_per_stage.v3.py", line 29, in get_original_readcount
    with open(fastq, 'r') as f1:
FileNotFoundError: [Errno 2] No such file or directory: './fastq/singles.fastq'
Traceback (most recent call last):
  File "/NGStools/StrainXpress/scripts/fastq2fasta.py", line 43, in <module>
    sys.exit(main())
  File "/NGStools/StrainXpress/scripts/fastq2fasta.py", line 32, in main
    with open(infile, 'r') as f1:
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/beegfs/scratch/ONEIDA/oneida/smallfiles-64k/cimendes/BMock12/downsample_10_percent/LMAS/work/03/768fdf1434252cf3f39a5485e49867/stageb/singles.fastq'
rm: cannot remove 'contigs_b.fasta': No such file or directory
rm: cannot remove 'contigs_b.fastq': No such file or directory
rm: cannot remove 'contigs_b.fa': No such file or directory
rm: cannot remove 'graph*': No such file or directory
rm: cannot remove 'p*': No such file or directory
successfully execute: split SRR8073716_reads.fq -l 21333872 -d -a 2 sub
successfully execute: cat cmd_overlap.sh | xargs -i -P 8 bash -c "{}";
successfully execute: for X in sub*.map; do sort  -k3 -nr < $X > sorted-$X; done;
successfully execute: sort -k3 -nr -m sorted-sub*.map > all_reads_sort.map;
successfully execute: rm *sub*;
successfully execute: python /NGStools/StrainXpress/scripts/get_readnames.py SRR8073716_reads.fq readnames.txt
successfully execute: python /NGStools/StrainXpress/scripts/bin_pointer_limited_filechunks_shortpath.py all_reads_sort.map readnames.txt 15000 strainxpress 8
successfully execute: python /NGStools/StrainXpress/scripts/getclusters.py strainxpress_max15000_final 8
successfully execute: python /NGStools/StrainXpress/scripts/get_fq_cluster.py strainxpress_max15000_final_clusters_grouped.json SRR8073716_reads.fq /mnt/beegfs/scratch/ONEIDA/oneida/smallfiles-64k/cimendes/BMock12/downsample_10_percent/LMAS/work/03/768fdf1434252cf3f39a5485e49867/fq_15000
successfully execute: rm -rf Chunkfile*; rm strainxpress_max15000_final_clustersizes.json strainxpress_max15000_final_clusters_unchained.json strainxpress_max15000_final_clusters.json
successfully execute: cat cmd_polyte.sh | xargs -i -P 8 bash -c "{}";
Don't execute the command: cat /mnt/beegfs/scratch/ONEIDA/oneida/smallfiles-64k/cimendes/BMock12/downsample_10_percent/LMAS/work/03/768fdf1434252cf3f39a5485e49867/fq_15000/*/contigs.fasta > all.contigs_15000.fasta cat: '/mnt/beegfs/scratch/ONEIDA/oneida/smallfiles-64k/cimendes/BMock12/downsample_10_percent/LMAS/work/03/768fdf1434252cf3f39a5485e49867/fq_15000/*/contigs.fasta': No such file or directory

successfully execute: mkdir -p stageb
successfully execute: cd stageb; minimap2 -t 8 --sr -X -c -k 21 -w 11 -s 60 -m 30 -n 2 -r 0      -A 4 -B 2 --end-bonus=100 ../contigs_b.fastq ../contigs_b.fastq | python /NGStools/StrainXpress/scripts/filter_trans_ovlp_inline_v3.py       -len 100 -iden 0.99 -oh 2 -sfo > sfoverlaps.out;
successfully execute: cd stageb; python /NGStools/StrainXpress/scripts/sfo2overlaps.py --in sfoverlaps.out     --out sfoverlap.out.savage --num_singles 0 --num_pairs 0; mkdir -p fastq;    cp ../contigs_b.fastq ./fastq/singles.fastq;
successfully execute: cd stageb; python /NGStools/StrainXpress/scripts/pipeline_per_stage.v3.py --no_error_correction --remove_branches true      --stage b --min_overlap_len 100 --min_overlap_perc 0 --edge_threshold 1 --overlaps ./sfoverlap.out.savage      --fastq ./fastq --max_tip_len 1000 --num_threads 8; python /NGStools/StrainXpress/scripts/fastq2fasta.py ./singles.fastq      ./final_contigs.fasta; rm -r contigs_b.fasta contigs_b.fastq contigs_b.fa  fastq graph* p* s*;
mv: cannot stat 'stageb/final_contigs.fasta': No such file or directory
```
I appreciate any help regarding this error.

Best regards,
Inês

**Comment by kangxiongbin** [comment]
Hi Inês,
Can you let me see the reads's name in your fq file (10 are enough)? I think maybe strainxpress is fail to class the reads beacuse the format of reads.

**Comment by cimendes** [comment]
hello! This is how I'm interleaving my reads for strainXpress (using bbtools):

reformat.sh in=${fastq_pair[0]} in2=${fastq_pair[1]} out=${sample_id}_reads.fq

Here are the top 10 reads from my file  (had to compress the file to attach it, but I'm running it uncompressed

[head_SRR8073716_reads.fq.zip](https://github.com/kangxiongbin/StrainXpress/files/9776022/head_SRR8073716_reads.fq.zip)

**Comment by kangxiongbin** [comment]
Please delete the spade in the read's name
Take the first read as example: 
change @SRR8073716.20 20/1 and @SRR8073716.20 20/2 to @SRR8073716.2020/1 and @SRR8073716.2020/2 (or @SRR8073716.20/1 and @SRR8073716.20/2)

and then rerun strainxpress

**Comment by cimendes** [comment]
Thank you for the quick reply. 

I tried removing the spaces on the reads a sed command (`sed 's/ //g' $fasta_reads_single > nospaces_${sample_id}.fq`) and unfortunately the error still persists. I've attached the top 10 reads again [head_nospaces_SRR8073716_reads.fq.zip](https://github.com/kangxiongbin/StrainXpress/files/9838472/head_nospaces_SRR8073716_reads.fq.zip)

**Comment by kangxiongbin** [comment]
Sorry! I'm very busy recently. 
I think your format is right. Is the same error? Is it an uncompressed file? Python3 ?


> Thank you for the quick reply.
> 
> I tried removing the spaces on the reads a sed command (`sed 's/ //g' $fasta_reads_single > nospaces_${sample_id}.fq`) and unfortunately the error still persists. I've attached the top 10 reads again [head_nospaces_SRR8073716_reads.fq.zip](https://github.com/kangxiongbin/StrainXpress/files/9838472/head_nospaces_SRR8073716_reads.fq.zip)

**Comment by cimendes** [comment]
Hello! The file is uncompressed, yes, and as you can see from the docker container, available at https://github.com/B-UMMI/LMAS/blob/main/docker/strainXpress/Dockerfile and in the [docker hub registry](https://hub.docker.com/r/cimendes/strainxpress/tags). I'm using python3 (I followed the installation instructions available on this repository). 

Given that you've analysed this dataset in your NAR manuscript, I don't understand why I'm not being able to reproduce your results. Sorry for the trouble and thank you for your assistance!

**Comment by ramirma** [comment]
Any news regarding this issue? We would really like to reproduce the analysis in the manuscript and integrate the assembler into our [LMAS ](https://github.com/B-UMMI/LMAS/pull/32) platform

**Comment by kangxiongbin** [comment]
> Hello! The file is uncompressed, yes, and as you can see from the docker container, available at https://github.com/B-UMMI/LMAS/blob/main/docker/strainXpress/Dockerfile and in the [docker hub registry](https://hub.docker.com/r/cimendes/strainxpress/tags). I'm using python3 (I followed the installation instructions available on this repository).
> 
> Given that you've analysed this dataset in your NAR manuscript, I don't understand why I'm not being able to reproduce your results. Sorry for the trouble and thank you for your assistance!

Sorry! recently I'm super busy and reply you later.
After you change the reads' name, does it report the same issue? The issue means the clustering methods don't work. before Strainxpress assemble reads, it would like to cluster reads stemming from identical species. Please check the log file again. Or you give me a small sub fq file of your Bemock12 reads? I can help you if it works in my computer. I also very confuse why it doesn't work. Can you successfully process the example with Strainxpress in my github?

**Comment by cimendes** [comment]
> After you change the reads' name, does it report the same issue?

Yes, it does. Did you have to replace the reads' names for the manuscript? Just wondering as read preprocessing isn't covered in your manuscript. 

>Can you successfully process the example with Strainxpress in my github?

I've just tested the container using the read dataset available https://github.com/kangxiongbin/StrainXpress/blob/main/example/all_reads.fq and it works. I believe this means that the problem is not on my docker container for StrainXpress. I've included the stdout of the run. [log.txt](https://github.com/kangxiongbin/StrainXpress/files/10194746/log.txt)

**Comment by cimendes** [comment]
Hello! Happy new year! Just wondering if you have been able to reproduce my error? Did you manage to download the read files that I've uploaded to this issue? 
Thank you!

**Comment by kangxiongbin** [comment]
> > After you change the reads' name, does it report the same issue?
> 
> Yes, it does. Did you have to replace the reads' names for the manuscript? Just wondering as read preprocessing isn't covered in your manuscript.
> 
> > Can you successfully process the example with Strainxpress in my github?
> 
> I've just tested the container using the read dataset available https://github.com/kangxiongbin/StrainXpress/blob/main/example/all_reads.fq and it works. I believe this means that the problem is not on my docker container for StrainXpress. I've included the stdout of the run. [log.txt](https://github.com/kangxiongbin/StrainXpress/files/10194746/log.txt)

Happy new year! I also replace the reads' name for the bmock12. Base on your log.txt, you docker cantainer can successfully process the example.

**Comment by ramirma** [comment]
Thank you for getting back to us on this @kangxiongbin . Do you have a repository where you have the renamed reads of bmock12 that we could use or perhaps just the head of the renamed file so we can understand what changes need to be introduced?

**Comment by kangxiongbin** [comment]
I retain a sub sample and think it will work. 

https://drive.google.com/file/d/1GWuSp5zXyqHs9r6gFlQPJtos4S3vFHq5/view?usp=sharing



> Thank you for getting back to us on this @kangxiongbin . Do you have a repository where you have the renamed reads of bmock12 that we could use or perhaps just the head of the renamed file so we can understand what changes need to be introduced?

**Comment by cimendes** [comment]
Hello @kangxiongbin
Unfortunately I still get the same error even with your dataset. I've compared the read names and they're equal to mine so I don't think that's the problem. :/ Please see images attached:
<img width="566" alt="image" src="https://user-images.githubusercontent.com/15690332/214892463-c67e3f65-a31c-4de7-bb66-23a564a89e3a.png">
<img width="1431" alt="Screenshot 2023-01-26 at 16 08 46" src="https://user-images.githubusercontent.com/15690332/214892499-60728208-4d97-4c06-b174-dd77beedb8e9.png">

**Comment by kangxiongbin** [comment]
> Hello @kangxiongbin Unfortunately I still get the same error even with your dataset. I've compared the read names and they're equal to mine so I don't think that's the problem. :/ Please see images attached: <img alt="image" width="566" src="https://user-images.githubusercontent.com/15690332/214892463-c67e3f65-a31c-4de7-bb66-23a564a89e3a.png"> <img alt="Screenshot 2023-01-26 at 16 08 46" width="1431" src="https://user-images.githubusercontent.com/15690332/214892499-60728208-4d97-4c06-b174-dd77beedb8e9.png">

It seems like a script don't work: python get_readnames.py < fq file > readnames.txt. 

Did you uncompress the file sub_read2.fq.gz ?

Can you check if the file readnames.txt is existed? It supposed contain the name of reads (delete the /1 /2)

Can you run the command to generate the readnames.txt file by python get_readnames.py sub_read2.fq readnames.txt ?

**Comment by cimendes** [comment]
<img width="1435" alt="Screenshot 2023-01-27 at 11 19 01" src="https://user-images.githubusercontent.com/15690332/215074125-edfe99dc-15a3-4a38-a874-673344d8eff8.png">
Hello! I've rerun this multiple times just in case it was something on my side but as you can see from the error message i've attached, the `sub_read2.fq` file gets deleted and the `readnames.txt` fails to be generated. This is a really weird error, and different from what I obtain with my read set.

**Comment by ramirma** [comment]
@kangxiongbin can you confirm that you complete a run with your dataset? We have already tried running in two different machines and get the same error suggesting it is not a local configuration problem.

**Comment by kangxiongbin** [comment]
> @kangxiongbin can you confirm that you complete a run with your dataset? We have already tried running in two different machines and get the same error suggesting it is not a local configuration problem.

Thanks for using StrainXpress. Recently, I take time to download this version and check what's problem

**Comment by kangxiongbin** [comment]
> <img alt="Screenshot 2023-01-27 at 11 19 01" width="1435" src="https://user-images.githubusercontent.com/15690332/215074125-edfe99dc-15a3-4a38-a874-673344d8eff8.png">
> 
> Hello! I've rerun this multiple times just in case it was something on my side but as you can see from the error message i've attached, the `sub_read2.fq` file gets deleted and the `readnames.txt` fails to be generated. This is a really weird error, and different from what I obtain with my read set.

Can you change the name of reads file (sub_read2.fq) to all_reads.fq and rerun StrainXpress  again? I found that the name of fq file shouldn't contain "sub". Because StrainXpress will delete intermediate file, which named sub_*.

**Comment by kangxiongbin** [comment]
> Hello! I've rerun this multiple times just in case it was something on my side but as you can see from the error message i've attached, the `sub_read2.fq` file gets deleted and the `readnames.txt` fails to be generated. This is a really weird error, and different from what I obtain with my read set.

If StrainXpress still don't work, I'll rerun and check it. Sorry! Recently, I'm busy with my dissertation and don't help you deal with the problem in time. I'm very happy for you wanna use our method.

Have a nice day!

**Comment by cimendes** [comment]
<img width="1435" alt="image" src="https://user-images.githubusercontent.com/15690332/216293330-799d35c7-0a05-42de-bc01-2b8a39ed071e.png">
Hello! I've tried assembling your dataset, after renaming it to remove the `sub_` part, and unfortunately, I ran into the same python error I described before. :/

**Comment by kangxiongbin** [comment]
> <img alt="image" width="1435" src="https://user-images.githubusercontent.com/15690332/216293330-799d35c7-0a05-42de-bc01-2b8a39ed071e.png">
> 
> Hello! I've tried assembling your dataset, after renaming it to remove the `sub_` part, and unfortunately, I ran into the same python error I described before. :/

How about filter out no ATCG base:
perl -ne'$n=$.%4; if($n eq 2){s/[^ATCG\n]/N/g; print;}else{print;};' sub_read2.fq > all_reads.fq

Tomorrow, I also download it in other server and take a try.
Thx

**Comment by Yaqiao-Li** [comment]
I ran into exactly the same error. 

cmd_polyte.sh: No such file or directory
[ERROR] failed to open file '../contigs_b.fastq'

**Comment by ramirma** [comment]
We were unable to complete a run of StrainXpress on the  BMock12 dataset even after following @kangxiongbin suggestion.

**Comment by kangxiongbin** [comment]
I thought you had successfully resolved the issue. I apologize for the delay as I've been quite busy with my graduation thesis lately. I will create a new conda environment, download and install StrainXpress, then re-download the data from bmock12 and rerun the process to identify the root of the problem. Please allow me one week to complete these tasks.

**Comment by ramirma** [comment]
Thank you. We will await your news.

**Comment by kangxiongbin** [comment]
I'd like to inquire if StrainXpress has been running smoothly with other data sets? If so, I'll download the raw data from bmock12 and test it now.

**Comment by ramirma** [comment]
No. We were never able to complete a run with StrainXpress

**Comment by kangxiongbin** [comment]
Hi,

Thank you for your patience! 

Today, following the instructions on StrainXpress on GitHub, I installed StrainXpress on another server. Then, I downloaded the Illumina data for Bmock12 from ENA using the following commands:
wget ftp://ftp.sra.ebi.ac.uk/vol1/fastq/SRR807/006/SRR8073716/SRR8073716_1.fastq.gz
wget ftp://ftp.sra.ebi.ac.uk/vol1/fastq/SRR807/006/SRR8073716/SRR8073716_2.fastq.gz

Next, I used fastp to perform quality control and merge the read1 and read2 files:
fastp -i SRR8073716_1.fastq.gz -I SRR8073716_2.fastq.gz -c --stdout > SRR8073716.fq

Then, I extracted 200,000 reads for testing, removing non-ATCG bases and modifying read names because StrainXpress clusters reads based on their names and names with spaces can affect later read identification and extraction:
head -1000000 SRR8073716.fq | perl -ne'if($.%4 eq 2){s/[^ATCG\n]/C/g; print;}elsif($.%4 eq 1){s/\s+//;print;}else{print};' > test.fq

Finally, I processed data with StrainXpress:
python ./StrainXpress/scripts/strainxpress.py -fq test.fq

The process ran smoothly, and the final assembly result file was provided in the "stageb" folder as final_contigs.fasta.

Lastly, I would like to suggest that, although StrainXpress can retain more strain-specific variants by assembling based on the overlap graph, its running speed is slow, especially for samples with high coverage. It is recommended to use a smaller number of reads for StrainXpress. I am currently optimizing this aspect, and I hope that the next version will run faster and not produce large intermediate files.

Thank you very much for your interest in StrainXpress!

**Comment by kangxiongbin** [comment]
Due to some special characters, GitHub automatically modified my code. Here, I will directly display an image of the code.

![image](https://user-images.githubusercontent.com/23208764/235358088-abc894a0-f590-4776-a2c2-476a44075b1f.png)
