### ISSUE TITLE
Working with long reads?

### ISSUE THREAD

**Issue by OZTaekOppa** [kangxiongbin/StrainXpress#7]
Hi,

Hope this email finds you well.

The GitHub page says the StrainXpress is based on the OLC paradigm. 

Given the circumstances, do you think it would be possible to test with PacBio and Oxford Nanopore datasets (either raw or error-corrected reads)? 

Looking forward to your reply!

Kind regards,

Taek

**Comment by centrohub22** [comment]
Hi, thanks for your interest. Theoretically,  the basic idea of StrainXpress should be applicable to long reads, in particular, high-quality long reads. But in reality, there may be some issues when running StrainXpress  on long-read data (we did not test yet), anyway, this is a promising project for future research.

**Comment by HaploKit** [comment]
Hi, thanks for your interest. Theoretically, the basic idea of StrainXpress should be applicable to long reads, in particular, high-quality long reads. But in reality, there may be some issues when running StrainXpress on long-read data (we did not test yet), anyway, this is a promising project for future research.
